apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "muffin-currency.fullname" . }}
  labels:
    {{- include "muffin-currency.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "muffin-currency.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "muffin-currency.labels" . | nindent 8 }}
    spec:
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: promtail-config
          configMap:
            name: promtail-config-currency


      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: log-volume
              mountPath: /logs
        
        - name: promtail
          image: grafana/promtail:latest
          args:
            - -config.file=/etc/promtail/promtail.yaml
          volumeMounts:
            - name: log-volume
              mountPath: /logs
            - name: promtail-config
              mountPath: /etc/promtail/promtail.yaml
              subPath: promtail.yaml
