repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: openzipkin
    url: https://openzipkin.github.io/zipkin-helm
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: loki
    namespace: monitoring
    chart: grafana/loki
    version: 6.51.0
    values:
      - logs-and-tracing/loki.yaml
    labels:
      component: monitoring
  
  - name: promtail
    namespace: monitoring
    chart: grafana/promtail
    version: 6.17.1
    values:
      - logs-and-tracing/promtail.yaml
    labels:
      component: monitoring

  - name: zipkin
    chart: openzipkin/zipkin
    version: 0.4.0
    namespace: monitoring
    values:
      - logs-and-tracing/zipkin.yaml 

  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    version: 10.5.15
    values:
      - logs-and-tracing/grafana.yaml
    labels:
      component: monitoring

  - name: muffin-currency
    namespace: muffin
    chart: ./muffin-currency
    values:
      - ./muffin-currency/values.yaml

  - name: muffin-wallet
    namespace: muffin
    chart: ./muffin-wallet
    values:
      - ./muffin-wallet/values.yaml
    needs:
      - muffin/muffin-currency

  # - name: muffin-istio
  #   namespace: muffin
  #   chart: ./muffin-istio
  #   values:
  #     - ./muffin-istio/values.yaml
  #   needs:
  #     - muffin/muffin-wallet
  #     - muffin/muffin-currency
