{{- if .Values.externalDb.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-postgres
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.externalDb.host | quote }}
  ports:
    - number: {{ .Values.externalDb.port }}
      name: tcp-postgres
      protocol: {{ .Values.externalDb.protocol }}
  location: MESH_EXTERNAL
  resolution: DNS
{{- end }}
