version: '3.9'

services:
  postgres:
    container_name: muffin-postgres2
    image: postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=muffin-wallet
      - POSTGRES_PASSWORD=muffin-wallet
      - POSTGRES_DB=muffin_wallet
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data2

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: host

  # loki:
  #   image: grafana/loki:latest
  #   container_name: loki
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml
  #   network_mode: host

  # promtail:
  #   image: grafana/promtail:latest
  #   container_name: promtail
  #   volumes:
  #     - ../muffin-wallet-server/logs:/var/log/app:ro
  #     - ./promtail-config-local.yaml:/etc/promtail/config.yaml
  #   command: -config.file=/etc/promtail/config.yaml
  #   network_mode: host

  # grafana:
  #   ports:
  #     - "3000:3000"
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   restart: unless-stopped
  #   network_mode: host

  # zipkin:
  #   image: openzipkin/zipkin:latest
  #   container_name: zipkin
  #   ports:
  #     - "9411:9411"
  #   restart: unless-stopped
  #   network_mode: host

volumes:
  db_data:
