apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "muffin-wallet.fullname" . }}-config
data:
  application.yaml: |
    server:
      port: {{ .Values.containerPort }}
    spring:
      application: 
        name: "muffin-wallet"
      datasource:
        url: {{ .Values.datasource.url }}
        username: {{ .Values.datasource.username }}

    currency:
      service:
        url: {{ .Values.currency.url }}

    logging:
      pattern:
        level: "%5p [%X{traceId:-},%X{spanId:-}]"
      file:
        name: {{ .Values.logging.file }}

    management:
      tracing:
        sampling:
          probability: 1.0 # Sample 100% of traces for demo
      zipkin:
        tracing: 
          endpoint: "http://zipkin.monitoring.svc.cluster.local:9411/api/v2/spans" # Zipkin's v2 API
      endpoints:
        web:
          exposure:
            include: '*'
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always

    management.metrics.distribution.percentiles-histogram.http.server.requests: true
