apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceLog.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "muffin-wallet.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.serviceLog.port }}
      targetPort: {{ .Values.serviceLog.targetPort }}